"""empty message

Revision ID: f5363b5a1408
Revises: 
Create Date: 2023-12-27 10:32:01.647149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5363b5a1408'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perawat',
    sa.Column('npm_perawat', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=False),
    sa.Column('jabatan', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('npm_perawat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perawat')
    # ### end Alembic commands ###
